/* Lab1 */

SELECT B_TITLE, B_PRICE, B_CIRCUL
FROM Books

SELECT A_LNAME, A_FNAME, A_ADDR
FROM Authors

SELECT E_LNAME, E_FNAME, E_BORN
FROM Employees

SELECT E_LNAME, E_FNAME
FROM Employees
WHERE E_SEX = 'М'

SELECT DISTINCT B_EDIT
FROM Books 

SELECT *
FROM Employees
WHERE DATEPART(YEAR, E_BORN) = 2010 AND DATEPART(MONTH, E_BORN) = 5

SELECT E_FNAME, E_LNAME
FROM Employees
WHERE E_ADDR != 'Москва' AND E_ROOM = 3

SELECT O_COMPANY
FROM Orders
WHERE O_DATE = '10.08.2020'

SELECT *
FROM Authors
WHERE A_LNAME BETWEEN 'А' AND 'И'

SELECT B_TITLE, B_PRICE, B_CIRCUL
FROM Books
ORDER BY B_PRICE DESC

SELECT MAX(P_SAL)
FROM Posts

SELECT O_ID, COUNT(B_ID) AS BOOKS
FROM Items
GROUP BY O_ID



